export const COUNTRIES = [
  {
    name: "Aland Islands",
    altNames: ["Wyspy Alandzkie", "Ålandinseln", "Îles d'Aland", "Islas Åland"],
    countryCode: "ax",
    flagColors: ["#0053a5", "#ffce00"],
  },
  {
    name: "Albania",
    altNames: ["Albania", "Albanien", "Albanie", "Albania"],
    countryCode: "al",
    flagColors: ["#e41e20", "#000000"],
  },
  {
    name: "Andorra",
    altNames: ["Andora", "Andorra", "Andorre", "Andorra"],
    countryCode: "ad",
    flagColors: ["#0033a0", "#fedd00"],
  },
  {
    name: "Austria",
    altNames: ["Austria", "Österreich", "Autriche", "Austria"],
    countryCode: "at",
    flagColors: ["#ed2939", "#ffffff"],
  },
  {
    name: "Belarus",
    altNames: ["Białoruś", "Belarus", "Biélorussie", "Bielorrusia"],
    countryCode: "by",
    flagColors: ["#cf101a", "#009739"],
  },
  {
    name: "Belgium",
    altNames: ["Belgia", "Belgien", "Belgique", "Bélgica"],
    countryCode: "be",
    flagColors: ["#000000", "#fde100"],
  },
  {
    name: "Bosnia and Herzegovina",
    altNames: ["Bośnia i Hercegowina", "Bosnien und Herzegowina", "Bosnie-Herzégovine", "Bosnia y Herzegovina"],
    countryCode: "ba",
    flagColors: ["#002395", "#fecb00"],
  },
  {
    name: "Bulgaria",
    altNames: ["Bułgaria", "Bulgarien", "Bulgarie", "Bulgaria"],
    countryCode: "bg",
    flagColors: ["#ffffff", "#00966e"],
  },
  {
    name: "Croatia",
    altNames: ["Chorwacja", "Kroatien", "Croatie", "Croacia"],
    countryCode: "hr",
    flagColors: ["#ff0000", "#ffffff"],
  },
  {
    name: "Cyprus",
    altNames: ["Cypr", "Zypern", "Chypre", "Chipre"],
    countryCode: "cy",
    flagColors: ["#ffffff", "#d47008"],
  },
  {
    name: "Czech Republic",
    altNames: ["Czechy", "Tschechien", "République tchèque", "República Checa"],
    countryCode: "cz",
    flagColors: ["#ffffff", "#d7141a"],
  },
  {
    name: "Denmark",
    altNames: ["Dania", "Dänemark", "Danemark", "Dinamarca"],
    countryCode: "dk",
    flagColors: ["#c60c30", "#ffffff"],
  },
  {
    name: "Estonia",
    altNames: ["Estonia", "Estland", "Estonie", "Estonia"],
    countryCode: "ee",
    flagColors: ["#0072ce", "#000000"],
  },
  {
    name: "Faroe Islands",
    altNames: ["Wyspy Owcze", "Färöer", "Îles Féroé", "Islas Feroe"],
    countryCode: "fo",
    flagColors: ["#ffffff", "#0065bd"],
  },
  {
    name: "Finland",
    altNames: ["Finlandia", "Finnland", "Finlande", "Finlandia"],
    countryCode: "fi",
    flagColors: ["#ffffff", "#003580"],
  },
  {
    name: "France",
    altNames: ["Francja", "Frankreich", "France", "Francia"],
    countryCode: "fr",
    flagColors: ["#002395", "#ed2939"],
  },
  {
    name: "Germany",
    altNames: ["Niemcy", "Deutschland", "Allemagne", "Alemania"],
    countryCode: "de",
    flagColors: ["#000000", "#dd0000"],
  },
  {
    name: "Gibraltar",
    altNames: ["Gibraltar", "Gibraltar", "Gibraltar", "Gibraltar"],
    countryCode: "gi",
    flagColors: ["#ffffff", "#da121a"],
  },
  {
    name: "Greece",
    altNames: ["Grecja", "Griechenland", "Grèce", "Grecia"],
    countryCode: "gr",
    flagColors: ["#0d5eaf", "#ffffff"],
  },
  {
    name: "Guernsey",
    altNames: ["Guernsey", "Guernsey", "Guernesey", "Guernesey"],
    countryCode: "gg",
    flagColors: ["#ffffff", "#e8112d"],
  },
  {
    name: "Holy See",
    altNames: ["Watykan", "Vatikanstadt", "Saint-Siège", "Santa Sede"],
    countryCode: "va",
    flagColors: ["#ffe000", "#ffffff"],
  },
  {
    name: "Hungary",
    altNames: ["Węgry", "Ungarn", "Hongrie", "Hungría"],
    countryCode: "hu",
    flagColors: ["#ce1126", "#ffffff"],
  },
  {
    name: "Iceland",
    altNames: ["Islandia", "Island", "Islande", "Islandia"],
    countryCode: "is",
    flagColors: ["#003897", "#d72828"],
  },
  {
    name: "Ireland",
    altNames: ["Irlandia", "Irland", "Irlande", "Irlanda"],
    countryCode: "ie",
    flagColors: ["#169b62", "#ff883e"],
  },
  {
    name: "Isle of Man",
    altNames: ["Wyspa Man", "Isle of Man", "Île de Man", "Isla de Man"],
    countryCode: "im",
    flagColors: ["#cf1020", "#ffffff"],
  },
  {
    name: "Italy",
    altNames: ["Włochy", "Italien", "Italie", "Italia"],
    countryCode: "it",
    flagColors: ["#009246", "#ffffff"],
  },
  {
    name: "Jersey",
    altNames: ["Jersey", "Jersey", "Jersey", "Jersey"],
    countryCode: "je",
    flagColors: ["#ffffff", "#da121a"],
  },
  {
    name: "Latvia",
    altNames: ["Łotwa", "Lettland", "Lettonie", "Letonia"],
    countryCode: "lv",
    flagColors: ["#9e3039", "#ffffff"],
  },
  {
    name: "Liechtenstein",
    altNames: ["Liechtenstein", "Liechtenstein", "Liechtenstein", "Liechtenstein"],
    countryCode: "li",
    flagColors: ["#002780", "#cf0921"],
  },
  {
    name: "Lithuania",
    altNames: ["Litwa", "Litauen", "Lituanie", "Lituania"],
    countryCode: "lt",
    flagColors: ["#fdb913", "#006a44"],
  },
  {
    name: "Luxembourg",
    altNames: ["Luksemburg", "Luxemburg", "Luxembourg", "Luxemburgo"],
    countryCode: "lu",
    flagColors: ["#ea141d", "#51adcf"],
  },
  {
    name: "Malta",
    altNames: ["Malta", "Malta", "Malte", "Malta"],
    countryCode: "mt",
    flagColors: ["#ffffff", "#cf142b"],
  },
  {
    name: "Moldova",
    altNames: ["Mołdawia", "Moldau", "Moldavie", "Moldavia"],
    countryCode: "md",
    flagColors: ["#0046ae", "#ffd200"],
  },
  {
    name: "Monaco",
    altNames: ["Monako", "Monaco", "Monaco", "Mónaco"],
    countryCode: "mc",
    flagColors: ["#ce1126", "#ffffff"],
  },
  {
    name: "Montenegro",
    altNames: ["Czarnogóra", "Montenegro", "Monténégro", "Montenegro"],
    countryCode: "me",
    flagColors: ["#c1272d", "#d0ae3d"],
  },
  {
    name: "Netherlands",
    altNames: ["Holandia", "Niederlande", "Pays-Bas", "Países Bajos"],
    countryCode: "nl",
    flagColors: ["#ae1c28", "#ffffff"],
  },
  {
    name: "North Macedonia",
    altNames: ["Macedonia Północna", "Nordmazedonien", "Macédoine du Nord", "Macedonia del Norte"],
    countryCode: "mk",
    flagColors: ["#d20000", "#ffe300"],
  },
  {
    name: "Norway",
    altNames: ["Norwegia", "Norwegen", "Norvège", "Noruega"],
    countryCode: "no",
    flagColors: ["#ba0c2f", "#00205b"],
  },
  {
    name: "Poland",
    altNames: ["Polska", "Polen", "Pologne", "Polonia"],
    countryCode: "pl",
    flagColors: ["#ffffff", "#dc143c"],
  },
  {
    name: "Portugal",
    altNames: ["Portugalia", "Portugal", "Portugal", "Portugal"],
    countryCode: "pt",
    flagColors: ["#006600", "#ff0000"],
  },
  {
    name: "Romania",
    altNames: ["Rumunia", "Rumänien", "Roumanie", "Rumania"],
    countryCode: "ro",
    flagColors: ["#002b7f", "#fcd116"],
  },
  {
    name: "Russia",
    altNames: ["Rosja", "Russland", "Russie", "Rusia"],
    countryCode: "ru",
    flagColors: ["#ffffff", "#0039a6"],
  },
  {
    name: "San Marino",
    altNames: ["San Marino", "San Marino", "Saint-Marin", "San Marino"],
    countryCode: "sm",
    flagColors: ["#ffffff", "#5eb1e4"],
  },
  {
    name: "Serbia",
    altNames: ["Serbia", "Serbien", "Serbie", "Serbia"],
    countryCode: "rs",
    flagColors: ["#c6363c", "#ffffff"],
  },
  {
    name: "Slovakia",
    altNames: ["Słowacja", "Slowakei", "Slovaquie", "Eslovaquia"],
    countryCode: "sk",
    flagColors: ["#ffffff", "#0b4ea2"],
  },
  {
    name: "Slovenia",
    altNames: ["Słowenia", "Slowenien", "Slovénie", "Eslovenia"],
    countryCode: "si",
    flagColors: ["#ffffff", "#0000ff"],
  },
  {
    name: "Spain",
    altNames: ["Hiszpania", "Spanien", "Espagne", "España"],
    countryCode: "es",
    flagColors: ["#aa151b", "#f1bf00"],
  },
  {
    name: "Svalbard and Jan Mayen",
    altNames: ["Svalbard i Jan Mayen", "Svalbard und Jan Mayen", "Svalbard et Jan Mayen", "Svalbard y Jan Mayen"],
    countryCode: "sj",
    flagColors: ["#ba0c2f", "#00205b"],
  },
  {
    name: "Sweden",
    altNames: ["Szwecja", "Schweden", "Suède", "Suecia"],
    countryCode: "se",
    flagColors: ["#006aa7", "#fecc00"],
  },
  {
    name: "Switzerland",
    altNames: ["Szwajcaria", "Schweiz", "Suisse", "Suiza"],
    countryCode: "ch",
    flagColors: ["#da291c", "#ffffff"],
  },
  {
    name: "Ukraine",
    altNames: ["Ukraina", "Ukraine", "Ukraine", "Ucrania"],
    countryCode: "ua",
    flagColors: ["#0057b7", "#ffd700"],
  },
  {
    name: "United Kingdom",
    altNames: ["Wielka Brytania", "Vereinigtes Königreich", "Royaume-Uni", "Reino Unido"],
    countryCode: "gb",
    flagColors: ["#012169", "#c8102e"],
  },
  {
    name: "England",
    altNames: ["Anglia", "England", "Angleterre", "Inglaterra"],
    countryCode: "gb-eng",
    flagColors: ["#ffffff", "#ce1124"],
  },
  {
    name: "Kosovo",
    altNames: ["Kosowo", "Kosovo", "Kosovo", "Kosovo"],
    countryCode: "xk",
    flagColors: ["#244aa5", "#d0a650"],
  },
  {
    name: "Northern Ireland",
    altNames: ["Irlandia Północna", "Nordirland", "Irlande du Nord", "Irlanda del Norte"],
    countryCode: "gb-nir",
    flagColors: ["#ffffff", "#ce1124"],
  },
  {
    name: "Scotland",
    altNames: ["Szkocja", "Schottland", "Écosse", "Escocia"],
    countryCode: "gb-sct",
    flagColors: ["#005eb8", "#ffffff"],
  },
  {
    name: "Wales",
    altNames: ["Walia", "Wales", "Pays de Galles", "Gales"],
    countryCode: "gb-wls",
    flagColors: ["#ffffff", "#00ad36"],
  },
  {
    name: "Algeria",
    altNames: ["Algieria", "Algerien", "Algérie", "Argelia"],
    countryCode: "dz",
    flagColors: ["#006233", "#ffffff"],
  },
  {
    name: "Angola",
    altNames: ["Angola", "Angola", "Angola", "Angola"],
    countryCode: "ao",
    flagColors: ["#ce1126", "#000000"],
  },
  {
    name: "Benin",
    altNames: ["Benin", "Benin", "Bénin", "Benín"],
    countryCode: "bj",
    flagColors: ["#008751", "#fcd116"],
  },
  {
    name: "Botswana",
    altNames: ["Botswana", "Botswana", "Botswana", "Botsuana"],
    countryCode: "bw",
    flagColors: ["#6da9d2", "#000000"],
  },
  {
    name: "Burkina Faso",
    altNames: ["Burkina Faso", "Burkina Faso", "Burkina Faso", "Burkina Faso"],
    countryCode: "bf",
    flagColors: ["#ef2b2d", "#009e49"],
  },
  {
    name: "Burundi",
    altNames: ["Burundi", "Burundi", "Burundi", "Burundi"],
    countryCode: "bi",
    flagColors: ["#ce1126", "#1eb53a"],
  },
  {
    name: "Cabo Verde",
    altNames: ["Republika Zielonego Przylądka", "Kap Verde", "Cap-Vert", "Cabo Verde"],
    countryCode: "cv",
    flagColors: ["#003893", "#ffffff"],
  },
  {
    name: "Cameroon",
    altNames: ["Kamerun", "Kamerun", "Cameroun", "Camerún"],
    countryCode: "cm",
    flagColors: ["#007a5e", "#ce1126"],
  },
  {
    name: "Central African Republic",
    altNames: ["Republika Środkowoafrykańska", "Zentralafrikanische Republik", "République centrafricaine", "República Centroafricana"],
    countryCode: "cf",
    flagColors: ["#003082", "#ffffff"],
  },
  {
    name: "Chad",
    altNames: ["Czad", "Tschad", "Tchad", "Chad"],
    countryCode: "td",
    flagColors: ["#002664", "#fecb00"],
  },
  {
    name: "Comoros",
    altNames: ["Komory", "Komoren", "Comores", "Comoras"],
    countryCode: "km",
    flagColors: ["#ffd700", "#ffffff"],
  },
  {
    name: "Côte d'Ivoire",
    altNames: ["Wybrzeże Kości Słoniowej", "Elfenbeinküste", "Côte d'Ivoire", "Costa de Marfil"],
    countryCode: "ci",
    flagColors: ["#ff8200", "#ffffff"],
  },
  {
    name: "Democratic Republic of the Congo",
    altNames: ["Demokratyczna Republika Konga", "Demokratische Republik Kongo", "République démocratique du Congo", "República Democrática del Congo"],
    countryCode: "cd",
    flagColors: ["#007fff", "#f7d417"],
  },
  {
    name: "Djibouti",
    altNames: ["Dżibuti", "Dschibuti", "Djibouti", "Yibuti"],
    countryCode: "dj",
    flagColors: ["#6ab2e7", "#12ad2b"],
  },
  {
    name: "Egypt",
    altNames: ["Egipt", "Ägypten", "Égypte", "Egipto"],
    countryCode: "eg",
    flagColors: ["#ce1126", "#ffffff"],
  },
  {
    name: "Equatorial Guinea",
    altNames: ["Gwinea Równikowa", "Äquatorialguinea", "Guinée équatoriale", "Guinea Ecuatorial"],
    countryCode: "gq",
    flagColors: ["#319208", "#ffffff"],
  },
  {
    name: "Eritrea",
    altNames: ["Erytrea", "Eritrea", "Érythrée", "Eritrea"],
    countryCode: "er",
    flagColors: ["#ee2f35", "#00ad24"],
  },
  {
    name: "Eswatini",
    altNames: ["Eswatini", "Eswatini", "Eswatini", "Eswatini"],
    countryCode: "sz",
    flagColors: ["#3e5eb9", "#b10c0c"],
  },
  {
    name: "Ethiopia",
    altNames: ["Etiopia", "Äthiopien", "Éthiopie", "Etiopía"],
    countryCode: "et",
    flagColors: ["#078930", "#fcd116"],
  },
  {
    name: "French Southern Territories",
    altNames: ["Francuskie Terytoria Południowe i Antarktyczne", "Französische Süd- und Antarktisgebiete", "Terres australes et antarctiques françaises", "Tierras Australes y Antárticas Francesas"],
    countryCode: "tf",
    flagColors: ["#002395", "#ffffff"],
  },
  {
    name: "Gabon",
    altNames: ["Gabon", "Gabun", "Gabon", "Gabón"],
    countryCode: "ga",
    flagColors: ["#009e49", "#fcd116"],
  },
  {
    name: "Gambia",
    altNames: ["Gambia", "Gambia", "Gambie", "Gambia"],
    countryCode: "gm",
    flagColors: ["#ce1126", "#0033aa"],
  },
  {
    name: "Ghana",
    altNames: ["Ghana", "Ghana", "Ghana", "Ghana"],
    countryCode: "gh",
    flagColors: ["#ce1126", "#fcd116"],
  },
  {
    name: "Guinea",
    altNames: ["Gwinea", "Guinea", "Guinée", "Guinea"],
    countryCode: "gn",
    flagColors: ["#ce1126", "#fcd116"],
  },
  {
    name: "Guinea-Bissau",
    altNames: ["Gwinea Bissau", "Guinea-Bissau", "Guinée-Bissau", "Guinea-Bisáu"],
    countryCode: "gw",
    flagColors: ["#ce1126", "#fcd116"],
  },
  {
    name: "Kenya",
    altNames: ["Kenia", "Kenia", "Kenya", "Kenia"],
    countryCode: "ke",
    flagColors: ["#000000", "#bb0000"],
  },
  {
    name: "Lesotho",
    altNames: ["Lesotho", "Lesotho", "Lesotho", "Lesoto"],
    countryCode: "ls",
    flagColors: ["#00209f", "#ffffff"],
  },
  {
    name: "Liberia",
    altNames: ["Liberia", "Liberia", "Libéria", "Liberia"],
    countryCode: "lr",
    flagColors: ["#bf0a30", "#ffffff"],
  },
  {
    name: "Libya",
    altNames: ["Libia", "Libyen", "Libye", "Libia"],
    countryCode: "ly",
    flagColors: ["#e70013", "#000000"],
  },
  {
    name: "Madagascar",
    altNames: ["Madagaskar", "Madagaskar", "Madagascar", "Madagascar"],
    countryCode: "mg",
    flagColors: ["#ffffff", "#fc3d32"],
  },
  {
    name: "Malawi",
    altNames: ["Malawi", "Malawi", "Malawi", "Malaui"],
    countryCode: "mw",
    flagColors: ["#000000", "#ce1126"],
  },
  {
    name: "Mali",
    altNames: ["Mali", "Mali", "Mali", "Mali"],
    countryCode: "ml",
    flagColors: ["#14b53a", "#fcd116"],
  },
  {
    name: "Mauritania",
    altNames: ["Mauretania", "Mauretanien", "Mauritanie", "Mauritania"],
    countryCode: "mr",
    flagColors: ["#006233", "#ffc400"],
  },
  {
    name: "Mauritius",
    altNames: ["Mauritius", "Mauritius", "Maurice", "Mauricio"],
    countryCode: "mu",
    flagColors: ["#ea1026", "#1a206d"],
  },
  {
    name: "Mayotte",
    altNames: ["Majotta", "Mayotte", "Mayotte", "Mayotte"],
    countryCode: "yt",
    flagColors: ["#ffffff", "#da121a"],
  },
  {
    name: "Morocco",
    altNames: ["Maroko", "Marokko", "Maroc", "Marruecos"],
    countryCode: "ma",
    flagColors: ["#c1272d", "#006233"],
  },
  {
    name: "Mozambique",
    altNames: ["Mozambik", "Mosambik", "Mozambique", "Mozambique"],
    countryCode: "mz",
    flagColors: ["#009739", "#000000"],
  },
  {
    name: "Namibia",
    altNames: ["Namibia", "Namibia", "Namibie", "Namibia"],
    countryCode: "na",
    flagColors: ["#003580", "#d21034"],
  },
  {
    name: "Niger",
    altNames: ["Niger", "Niger", "Niger", "Níger"],
    countryCode: "ne",
    flagColors: ["#e05206", "#ffffff"],
  },
  {
    name: "Nigeria",
    altNames: ["Nigeria", "Nigeria", "Nigéria", "Nigeria"],
    countryCode: "ng",
    flagColors: ["#008751", "#ffffff"],
  },
  {
    name: "Republic of the Congo",
    altNames: ["Kongo", "Republik Kongo", "République du Congo", "República del Congo"],
    countryCode: "cg",
    flagColors: ["#009543", "#fbde4a"],
  },
  {
    name: "Réunion",
    altNames: ["Reunion", "Réunion", "La Réunion", "Reunión"],
    countryCode: "re",
    flagColors: ["#002395", "#ffffff"],
  },
  {
    name: "Rwanda",
    altNames: ["Rwanda", "Ruanda", "Rwanda", "Ruanda"],
    countryCode: "rw",
    flagColors: ["#00a1de", "#fad201"],
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    altNames: ["Wyspa Świętej Heleny, Wyspa Wniebowstąpienia i Tristan da Cunha", "St. Helena, Ascension und Tristan da Cunha", "Sainte-Hélène, Ascension et Tristan da Cunha", "Santa Elena, Ascensión y Tristán de Acuña"],
    countryCode: "sh",
    flagColors: ["#002395", "#ffffff"],
  },
  {
    name: "Sao Tome and Principe",
    altNames: ["Wyspy Świętego Tomasza i Książęca", "São Tomé und Príncipe", "Sao Tomé-et-Principe", "Santo Tomé y Príncipe"],
    countryCode: "st",
    flagColors: ["#12ad2b", "#ffce00"],
  },
  {
    name: "Senegal",
    altNames: ["Senegal", "Senegal", "Sénégal", "Senegal"],
    countryCode: "sn",
    flagColors: ["#00853f", "#fdef42"],
  },
  {
    name: "Seychelles",
    altNames: ["Seszele", "Seychellen", "Seychelles", "Seychelles"],
    countryCode: "sc",
    flagColors: ["#003d88", "#fcd856"],
  },
  {
    name: "Sierra Leone",
    altNames: ["Sierra Leone", "Sierra Leone", "Sierra Leone", "Sierra Leona"],
    countryCode: "sl",
    flagColors: ["#1eb53a", "#ffffff"],
  },
  {
    name: "Somalia",
    altNames: ["Somalia", "Somalia", "Somalie", "Somalia"],
    countryCode: "so",
    flagColors: ["#4189dd", "#ffffff"],
  },
  {
    name: "South Africa",
    altNames: ["Republika Południowej Afryki", "Südafrika", "Afrique du Sud", "Sudáfrica"],
    countryCode: "za",
    flagColors: ["#007a4d", "#ffb81c"],
  },
  {
    name: "South Sudan",
    altNames: ["Sudan Południowy", "Südsudan", "Soudan du Sud", "Sudán del Sur"],
    countryCode: "ss",
    flagColors: ["#000000", "#da121a"],
  },
  {
    name: "Sudan",
    altNames: ["Sudan", "Sudan", "Soudan", "Sudán"],
    countryCode: "sd",
    flagColors: ["#d21034", "#ffffff"],
  },
  {
    name: "Tanzania",
    altNames: ["Tanzania", "Tansania", "Tanzanie", "Tanzania"],
    countryCode: "tz",
    flagColors: ["#1eb53a", "#fcd116"],
  },
  {
    name: "Togo",
    altNames: ["Togo", "Togo", "Togo", "Togo"],
    countryCode: "tg",
    flagColors: ["#006a4e", "#ffce00"],
  },
  {
    name: "Tunisia",
    altNames: ["Tunezja", "Tunesien", "Tunisie", "Túnez"],
    countryCode: "tn",
    flagColors: ["#e70013", "#ffffff"],
  },
  {
    name: "Uganda",
    altNames: ["Uganda", "Uganda", "Ouganda", "Uganda"],
    countryCode: "ug",
    flagColors: ["#000000", "#fcdc00"],
  },
  {
    name: "Western Sahara",
    altNames: ["Sahara Zachodnia", "Westsahara", "Sahara occidental", "Sahara Occidental"],
    countryCode: "eh",
    flagColors: ["#000000", "#ffffff"],
  },
  {
    name: "Zambia",
    altNames: ["Zambia", "Sambia", "Zambie", "Zambia"],
    countryCode: "zm",
    flagColors: ["#198a00", "#ef7d00"],
  },
  {
    name: "Zimbabwe",
    altNames: ["Zimbabwe", "Simbabwe", "Zimbabwe", "Zimbabue"],
    countryCode: "zw",
    flagColors: ["#319208", "#ffce00"],
  },
  {
    name: "Afghanistan",
    altNames: ["Afganistan", "Afghanistan", "Afghanistan", "Afganistán"],
    countryCode: "af",
    flagColors: ["#000000", "#bf0000"],
  },
  {
    name: "Armenia",
    altNames: ["Armenia", "Armenien", "Arménie", "Armenia"],
    countryCode: "am",
    flagColors: ["#d90012", "#0033a0"],
  },
  {
    name: "Azerbaijan",
    altNames: ["Azerbejdżan", "Aserbaidschan", "Azerbaïdjan", "Azerbaiyán"],
    countryCode: "az",
    flagColors: ["#0092bc", "#e4002b"],
  },
  {
    name: "Bahrain",
    altNames: ["Bahrajn", "Bahrain", "Bahreïn", "Baréin"],
    countryCode: "bh",
    flagColors: ["#ce1126", "#ffffff"],
  },
  {
    name: "Bangladesh",
    altNames: ["Bangladesz", "Bangladesch", "Bangladesh", "Bangladés"],
    countryCode: "bd",
    flagColors: ["#006a4e", "#f42a41"],
  },
  {
    name: "Bhutan",
    altNames: ["Bhutan", "Bhutan", "Bhoutan", "Bután"],
    countryCode: "bt",
    flagColors: ["#ffcd00", "#ff4e12"],
  },
  {
    name: "British Indian Ocean Territory",
    altNames: ["Brytyjskie Terytorium Oceanu Indyjskiego", "Britisches Territorium im Indischen Ozean", "Territoire britannique de l'océan Indien", "Territorio Británico del Océano Índico"],
    countryCode: "io",
    flagColors: ["#00247d", "#ffffff"],
  },
  {
    name: "Brunei Darussalam",
    altNames: ["Brunei", "Brunei", "Brunéi", "Brunéi"],
    countryCode: "bn",
    flagColors: ["#f7e017", "#000000"],
  },
  {
    name: "Cambodia",
    altNames: ["Kambodża", "Kambodscha", "Cambodge", "Camboya"],
    countryCode: "kh",
    flagColors: ["#032ea1", "#e00025"],
  },
  {
    name: "China",
    altNames: ["Chiny", "China", "Chine", "China"],
    countryCode: "cn",
    flagColors: ["#ee1c25", "#ffff00"],
  },
  {
    name: "Christmas Island",
    altNames: ["Wyspa Bożego Narodzenia", "Weihnachtsinsel", "Île Christmas", "Isla de Navidad"],
    countryCode: "cx",
    flagColors: ["#002395", "#008751"],
  },
  {
    name: "Cocos (Keeling) Islands",
    altNames: ["Wyspy Kokosowe", "Kokosinseln", "Îles Cocos", "Islas Cocos"],
    countryCode: "cc",
    flagColors: ["#008751", "#fcd116"],
  },
  {
    name: "Georgia",
    altNames: ["Gruzja", "Georgien", "Géorgie", "Georgia"],
    countryCode: "ge",
    flagColors: ["#ffffff", "#ff0000"],
  },
  {
    name: "Hong Kong",
    altNames: ["Hongkong", "Hongkong", "Hong Kong", "Hong Kong"],
    countryCode: "hk",
    flagColors: ["#ee1c25", "#ffffff"],
  },
  {
    name: "India",
    altNames: ["Indie", "Indien", "Inde", "India"],
    countryCode: "in",
    flagColors: ["#ff9933", "#128807"],
  },
  {
    name: "Indonesia",
    altNames: ["Indonezja", "Indonesien", "Indonésie", "Indonesia"],
    countryCode: "id",
    flagColors: ["#ff0000", "#ffffff"],
  },
  {
    name: "Iran",
    altNames: ["Iran", "Iran", "Iran", "Irán"],
    countryCode: "ir",
    flagColors: ["#239f40", "#ffffff"],
  },
  {
    name: "Iraq",
    altNames: ["Irak", "Irak", "Irak", "Irak"],
    countryCode: "iq",
    flagColors: ["#ce1126", "#ffffff"],
  },
  {
    name: "Israel",
    altNames: ["Izrael", "Israel", "Israël", "Israel"],
    countryCode: "il",
    flagColors: ["#ffffff", "#0038b8"],
  },
  {
    name: "Japan",
    altNames: ["Japonia", "Japan", "Japon", "Japón"],
    countryCode: "jp",
    flagColors: ["#ffffff", "#bc002d"],
  },
  {
    name: "Jordan",
    altNames: ["Jordania", "Jordanien", "Jordanie", "Jordania"],
    countryCode: "jo",
    flagColors: ["#000000", "#ffffff"],
  },
  {
    name: "Kazakhstan",
    altNames: ["Kazachstan", "Kasachstan", "Kazakhstan", "Kazajistán"],
    countryCode: "kz",
    flagColors: ["#00afca", "#fec52e"],
  },
  {
    name: "Kuwait",
    altNames: ["Kuwejt", "Kuwait", "Koweït", "Kuwait"],
    countryCode: "kw",
    flagColors: ["#007a3d", "#ffffff"],
  },
  {
    name: "Kyrgyzstan",
    altNames: ["Kirgistan", "Kirgisistan", "Kirghizistan", "Kirguistán"],
    countryCode: "kg",
    flagColors: ["#e30a17", "#ffed00"],
  },
  {
    name: "Laos",
    altNames: ["Laos", "Laos", "Laos", "Laos"],
    countryCode: "la",
    flagColors: ["#ce1126", "#002868"],
  },
  {
    name: "Lebanon",
    altNames: ["Liban", "Libanon", "Liban", "Líbano"],
    countryCode: "lb",
    flagColors: ["#ed1c24", "#ffffff"],
  },
  {
    name: "Macau",
    altNames: ["Makau", "Macau", "Macao", "Macao"],
    countryCode: "mo",
    flagColors: ["#00785e", "#ffffff"],
  },
  {
    name: "Malaysia",
    altNames: ["Malezja", "Malaysia", "Malaisie", "Malasia"],
    countryCode: "my",
    flagColors: ["#012169", "#cc0000"],
  },
  {
    name: "Maldives",
    altNames: ["Malediwy", "Malediven", "Maldives", "Maldivas"],
    countryCode: "mv",
    flagColors: ["#d21034", "#007e3a"],
  },
  {
    name: "Mongolia",
    altNames: ["Mongolia", "Mongolei", "Mongolie", "Mongolia"],
    countryCode: "mn",
    flagColors: ["#e01921", "#0066b3"],
  },
  {
    name: "Myanmar",
    altNames: ["Mjanma", "Myanmar", "Myanmar", "Myanmar"],
    countryCode: "mm",
    flagColors: ["#fecb00", "#34b233"],
  },
  {
    name: "Nepal",
    altNames: ["Nepal", "Nepal", "Népal", "Nepal"],
    countryCode: "np",
    flagColors: ["#dc143c", "#003893"],
  },
  {
    name: "North Korea",
    altNames: ["Korea Północna", "Nordkorea", "Corée du Nord", "Corea del Norte"],
    countryCode: "kp",
    flagColors: ["#024fa2", "#ed1c27"],
  },
  {
    name: "Oman",
    altNames: ["Oman", "Oman", "Oman", "Omán"],
    countryCode: "om",
    flagColors: ["#db161b", "#ffffff"],
  },
  {
    name: "Pakistan",
    altNames: ["Pakistan", "Pakistan", "Pakistan", "Pakistán"],
    countryCode: "pk",
    flagColors: ["#00401a", "#ffffff"],
  },
  {
    name: "Philippines",
    altNames: ["Filipiny", "Philippinen", "Philippines", "Filipinas"],
    countryCode: "ph",
    flagColors: ["#0038a8", "#ce1126"],
  },
  {
    name: "Qatar",
    altNames: ["Katar", "Katar", "Qatar", "Catar"],
    countryCode: "qa",
    flagColors: ["#8d1b3d", "#ffffff"],
  },
  {
    name: "Saudi Arabia",
    altNames: ["Arabia Saudyjska", "Saudi-Arabien", "Arabie saoudite", "Arabia Saudita"],
    countryCode: "sa",
    flagColors: ["#006c35", "#ffffff"],
  },
  {
    name: "Singapore",
    altNames: ["Singapur", "Singapur", "Singapour", "Singapur"],
    countryCode: "sg",
    flagColors: ["#ee1c25", "#ffffff"],
  },
  {
    name: "South Korea",
    altNames: ["Korea Południowa", "Südkorea", "Corée du Sud", "Corea del Sur"],
    countryCode: "kr",
    flagColors: ["#ffffff", "#000000"],
  },
  {
    name: "Sri Lanka",
    altNames: ["Sri Lanka", "Sri Lanka", "Sri Lanka", "Sri Lanka"],
    countryCode: "lk",
    flagColors: ["#8d153a", "#ffbe29"],
  },
  {
    name: "State of Palestine",
    altNames: ["Palestyna", "Palästina", "Palestine", "Palestina"],
    countryCode: "ps",
    flagColors: ["#000000", "#ffffff"],
  },
  {
    name: "Syria",
    altNames: ["Syria", "Syrien", "Syrie", "Siria"],
    countryCode: "sy",
    flagColors: ["#ce1126", "#ffffff"],
  },
  {
    name: "Taiwan",
    altNames: ["Tajwan", "Taiwan", "Taïwan", "Taiwán"],
    countryCode: "tw",
    flagColors: ["#fe0000", "#000095"],
  },
  {
    name: "Tajikistan",
    altNames: ["Tadżykistan", "Tadschikistan", "Tadjikistan", "Tayikistán"],
    countryCode: "tj",
    flagColors: ["#cc0000", "#ffffff"],
  },
  {
    name: "Thailand",
    altNames: ["Tajlandia", "Thailand", "Thaïlande", "Tailandia"],
    countryCode: "th",
    flagColors: ["#a51931", "#f4f5f8"],
  },
  {
    name: "Timor-Leste",
    altNames: ["Timor Wschodni", "Osttimor", "Timor oriental", "Timor Oriental"],
    countryCode: "tl",
    flagColors: ["#dc241f", "#000000"],
  },
  {
    name: "Türkiye",
    altNames: ["Turcja", "Türkei", "Turquie", "Turquía"],
    countryCode: "tr",
    flagColors: ["#e30a17", "#ffffff"],
  },
  {
    name: "Turkmenistan",
    altNames: ["Turkmenistan", "Turkmenistan", "Turkménistan", "Turkmenistán"],
    countryCode: "tm",
    flagColors: ["#009543", "#ed1c24"],
  },
  {
    name: "United Arab Emirates",
    altNames: ["Zjednoczone Emiraty Arabskie", "Vereinigte Arabische Emirate", "Émirats arabes unis", "Emiratos Árabes Unidos"],
    countryCode: "ae",
    flagColors: ["#ff0000", "#00732f"],
  },
  {
    name: "Uzbekistan",
    altNames: ["Uzbekistan", "Usbekistan", "Ouzbékistan", "Uzbekistán"],
    countryCode: "uz",
    flagColors: ["#0099b5", "#ffffff"],
  },
  {
    name: "Vietnam",
    altNames: ["Wietnam", "Vietnam", "Viêt Nam", "Vietnam"],
    countryCode: "vn",
    flagColors: ["#da251d", "#ffff00"],
  },
  {
    name: "Yemen",
    altNames: ["Jemen", "Jemen", "Yémen", "Yemen"],
    countryCode: "ye",
    flagColors: ["#ce1126", "#ffffff"],
  },
  {
    name: "Anguilla",
    altNames: ["Anguilla", "Anguilla", "Anguilla", "Anguila"],
    countryCode: "ai",
    flagColors: ["#002395", "#ffffff"],
  },
  {
    name: "Antigua and Barbuda",
    altNames: ["Antigua i Barbuda", "Antigua und Barbuda", "Antigua-et-Barbuda", "Antigua y Barbuda"],
    countryCode: "ag",
    flagColors: ["#000000", "#ce1126"],
  },
  {
    name: "Bahamas",
    altNames: ["Bahamy", "Bahamas", "Bahamas", "Bahamas"],
    countryCode: "bs",
    flagColors: ["#00778b", "#ffc72c"],
  },
  {
    name: "Barbados",
    altNames: ["Barbados", "Barbados", "Barbade", "Barbados"],
    countryCode: "bb",
    flagColors: ["#00267f", "#ffc72c"],
  },
  {
    name: "Belize",
    altNames: ["Belize", "Belize", "Belize", "Belice"],
    countryCode: "bz",
    flagColors: ["#003f87", "#ce1126"],
  },
  {
    name: "Bermuda",
    altNames: ["Bermudy", "Bermuda", "Bermudes", "Bermudas"],
    countryCode: "bm",
    flagColors: ["#bf0a30", "#ffffff"],
  },
  {
    name: "Canada",
    altNames: ["Kanada", "Kanada", "Canada", "Canadá"],
    countryCode: "ca",
    flagColors: ["#ff0000", "#ffffff"],
  },
  {
    name: "Cayman Islands",
    altNames: ["Kajmany", "Kaimaninseln", "Îles Caïmans", "Islas Caimán"],
    countryCode: "ky",
    flagColors: ["#00209f", "#ffffff"],
  },
  {
    name: "Costa Rica",
    altNames: ["Kostaryka", "Costa Rica", "Costa Rica", "Costa Rica"],
    countryCode: "cr",
    flagColors: ["#002b7f", "#ce1126"],
  },
  {
    name: "Cuba",
    altNames: ["Kuba", "Kuba", "Cuba", "Cuba"],
    countryCode: "cu",
    flagColors: ["#002590", "#cc0d0d"],
  },
  {
    name: "Dominica",
    altNames: ["Dominika", "Dominica", "Dominique", "Dominica"],
    countryCode: "dm",
    flagColors: ["#006b3f", "#fcd116"],
  },
  {
    name: "Dominican Republic",
    altNames: ["Dominikana", "Dominikanische Republik", "République dominicaine", "República Dominicana"],
    countryCode: "do",
    flagColors: ["#002d62", "#ce1126"],
  },
  {
    name: "El Salvador",
    altNames: ["Salwador", "El Salvador", "Salvador", "El Salvador"],
    countryCode: "sv",
    flagColors: ["#0047ab", "#ffffff"],
  },
  {
    name: "Greenland",
    altNames: ["Grenlandia", "Grönland", "Groenland", "Groenlandia"],
    countryCode: "gl",
    flagColors: ["#ffffff", "#ce1126"],
  },
  {
    name: "Grenada",
    altNames: ["Grenada", "Grenada", "Grenade", "Granada"],
    countryCode: "gd",
    flagColors: ["#fcd116", "#007a5e"],
  },
  {
    name: "Guadeloupe",
    altNames: ["Gwadelupa", "Guadeloupe", "Guadeloupe", "Guadalupe"],
    countryCode: "gp",
    flagColors: ["#002395", "#ed2939"], // Kolory flagi Francji (oficjalna)
  },
  {
    name: "Guatemala",
    altNames: ["Gwatemala", "Guatemala", "Guatemala", "Guatemala"],
    countryCode: "gt",
    flagColors: ["#4997d0", "#ffffff"],
  },
  {
    name: "Haiti",
    altNames: ["Haiti", "Haiti", "Haïti", "Haití"],
    countryCode: "ht",
    flagColors: ["#00209f", "#d21034"],
  },
  {
    name: "Honduras",
    altNames: ["Honduras", "Honduras", "Honduras", "Honduras"],
    countryCode: "hn",
    flagColors: ["#0073cf", "#ffffff"],
  },
  {
    name: "Jamaica",
    altNames: ["Jamajka", "Jamaika", "Jamaïque", "Jamaica"],
    countryCode: "jm",
    flagColors: ["#1ca630", "#ffce00"],
  },
  {
    name: "Martinique",
    altNames: ["Martynika", "Martinique", "Martinique", "Martinica"],
    countryCode: "mq",
    flagColors: ["#000000", "#157c3d"],
  },
  {
    name: "Mexico",
    altNames: ["Meksyk", "Mexiko", "Mexique", "México"],
    countryCode: "mx",
    flagColors: ["#006847", "#ce1126"],
  },
  {
    name: "Montserrat",
    altNames: ["Montserrat", "Montserrat", "Montserrat", "Montserrat"],
    countryCode: "ms",
    flagColors: ["#002395", "#ffffff"],
  },
  {
    name: "Nicaragua",
    altNames: ["Nikaragua", "Nicaragua", "Nicaragua", "Nicaragua"],
    countryCode: "ni",
    flagColors: ["#0067c6", "#ffffff"],
  },
  {
    name: "Panama",
    altNames: ["Panama", "Panama", "Panama", "Panamá"],
    countryCode: "pa",
    flagColors: ["#ffffff", "#da121a"],
  },
  {
    name: "Puerto Rico",
    altNames: ["Portoryko", "Puerto Rico", "Porto Rico", "Puerto Rico"],
    countryCode: "pr",
    flagColors: ["#ed1c24", "#0050ef"],
  },
  {
    name: "Saint Barthélemy",
    altNames: ["Saint-Barthélemy", "Saint-Barthélemy", "Saint-Barthélemy", "San Bartolomé"],
    countryCode: "bl",
    flagColors: ["#002395", "#ed2939"],
  },
  {
    name: "Saint Kitts and Nevis",
    altNames: ["Saint Kitts i Nevis", "St. Kitts und Nevis", "Saint-Christophe-et-Niévès", "San Cristóbal y Nieves"],
    countryCode: "kn",
    flagColors: ["#009e49", "#ce1126"],
  },
  {
    name: "Saint Lucia",
    altNames: ["Saint Lucia", "St. Lucia", "Sainte-Lucie", "Santa Lucía"],
    countryCode: "lc",
    flagColors: ["#66ccff", "#ffee00"],
  },
  {
    name: "Saint Martin",
    altNames: ["Saint-Martin", "Saint-Martin", "Saint-Martin", "San Martín"],
    countryCode: "mf",
    flagColors: ["#002395", "#ed2939"],
  },
  {
    name: "Saint Pierre and Miquelon",
    altNames: ["Saint-Pierre i Miquelon", "St. Pierre und Miquelon", "Saint-Pierre-et-Miquelon", "San Pedro y Miquelón"],
    countryCode: "pm",
    flagColors: ["#0052a5", "#ffffff"],
  },
  {
    name: "Saint Vincent and the Grenadines",
    altNames: ["Saint Vincent i Grenadyny", "St. Vincent und die Grenadinen", "Saint-Vincent-et-les-Grenadines", "San Vicente y las Granadinas"],
    countryCode: "vc",
    flagColors: ["#0072c6", "#fcd116"],
  },
  {
    name: "Sint Maarten",
    altNames: ["Sint Maarten", "Sint Maarten", "Sint Maarten", "Sint Maarten"],
    countryCode: "sx",
    flagColors: ["#ed2939", "#002395"],
  },
  {
    name: "Turks and Caicos Islands",
    altNames: ["Turks i Caicos", "Turks- und Caicosinseln", "Îles Turques-et-Caïques", "Islas Turcas y Caicos"],
    countryCode: "tc",
    flagColors: ["#002395", "#ffffff"],
  },
  {
    name: "United States Minor Outlying Islands",
    altNames: ["Dalekie Wyspy Mniejsze Stanów Zjednoczonych", "Kleinere Inselbesitzungen der Vereinigten Staaten", "Îles mineures éloignées des États-Unis", "Islas menores alejadas de los Estados Unidos"],
    countryCode: "um",
    flagColors: ["#bf0a30", "#002868"],
  },
  {
    name: "United States of America",
    altNames: ["Stany Zjednoczone", "Vereinigte Staaten", "États-Unis", "Estados Unidos"],
    countryCode: "us",
    flagColors: ["#bf0a30", "#002868"],
  },
  {
    name: "Virgin Islands (British)",
    altNames: ["Brytyjskie Wyspy Dziewicze", "Britische Jungferninseln", "Îles Vierges britanniques", "Islas Vírgenes Británicas"],
    countryCode: "vg",
    flagColors: ["#002395", "#ffffff"],
  },
  {
    name: "Virgin Islands (U.S.)",
    altNames: ["Wyspy Dziewicze Stanów Zjednoczonych", "Amerikanische Jungferninseln", "Îles Vierges des États-Unis", "Islas Vírgenes de los Estados Unidos"],
    countryCode: "vi",
    flagColors: ["#ffffff", "#f2a800"],
  },
  {
    name: "American Samoa",
    altNames: ["Samoa Amerykańskie", "Amerikanisch-Samoa", "Samoa américaines", "Samoa Americana"],
    countryCode: "as",
    flagColors: ["#002395", "#ffffff"],
  },
  {
    name: "Australia",
    altNames: ["Australia", "Australien", "Australie", "Australia"],
    countryCode: "au",
    flagColors: ["#00008b", "#ffffff"],
  },
  {
    name: "Cook Islands",
    altNames: ["Wyspy Cooka", "Cookinseln", "Îles Cook", "Islas Cook"],
    countryCode: "ck",
    flagColors: ["#002b7f", "#ffffff"],
  },
  {
    name: "Federated States of Micronesia",
    altNames: ["Mikronezja", "Mikronesien", "Micronésie", "Micronesia"],
    countryCode: "fm",
    flagColors: ["#75b2dd", "#ffffff"],
  },
  {
    name: "Fiji",
    altNames: ["Fidżi", "Fidschi", "Fidji", "Fiyi"],
    countryCode: "fj",
    flagColors: ["#61b2e4", "#ffffff"],
  },
  {
    name: "French Polynesia",
    altNames: ["Polinezja Francuska", "Französisch-Polynesien", "Polynésie française", "Polinesia Francesa"],
    countryCode: "pf",
    flagColors: ["#e00025", "#ffffff"],
  },
  {
    name: "Guam",
    altNames: ["Guam", "Guam", "Guam", "Guam"],
    countryCode: "gu",
    flagColors: ["#002395", "#ce1126"],
  },
  {
    name: "Kiribati",
    altNames: ["Kiribati", "Kiribati", "Kiribati", "Kiribati"],
    countryCode: "ki",
    flagColors: ["#ce1126", "#ffcc00"],
  },
  {
    name: "Marshall Islands",
    altNames: ["Wyspy Marshalla", "Marshallinseln", "Îles Marshall", "Islas Marshall"],
    countryCode: "mh",
    flagColors: ["#003893", "#ff9933"],
  },
  {
    name: "Nauru",
    altNames: ["Nauru", "Nauru", "Nauru", "Nauru"],
    countryCode: "nr",
    flagColors: ["#002b7f", "#ffc90e"],
  },
  {
    name: "New Caledonia",
    altNames: ["Nowa Kaledonia", "Neukaledonien", "Nouvelle-Calédonie", "Nueva Caledonia"],
    countryCode: "nc",
    flagColors: ["#2144ba", "#ffe500"], // Kolory flagi Kanaków (często stosowane zamiennie z FR)
  },
  {
    name: "New Zealand",
    altNames: ["Nowa Zelandia", "Neuseeland", "Nouvelle-Zélande", "Nueva Zelanda"],
    countryCode: "nz",
    flagColors: ["#00247d", "#cc142b"],
  },
  {
    name: "Niue",
    altNames: ["Niue", "Niue", "Niue", "Niue"],
    countryCode: "nu",
    flagColors: ["#fcd116", "#00247d"],
  },
  {
    name: "Norfolk Island",
    altNames: ["Norfolk", "Norfolkinsel", "Île Norfolk", "Isla Norfolk"],
    countryCode: "nf",
    flagColors: ["#006a4e", "#ffffff"],
  },
  {
    name: "Northern Mariana Islands",
    altNames: ["Mariany Północne", "Nördliche Marianen", "Îles Mariannes du Nord", "Islas Marianas del Norte"],
    countryCode: "mp",
    flagColors: ["#00bfff", "#ffffff"],
  },
  {
    name: "Palau",
    altNames: ["Palau", "Palau", "Palaos", "Palaos"],
    countryCode: "pw",
    flagColors: ["#4aadd6", "#ffde00"],
  },
  {
    name: "Papua New Guinea",
    altNames: ["Papua-Nowa Gwinea", "Papua-Neuguinea", "Papuasie-Nouvelle-Guinée", "Papúa Nueva Guinea"],
    countryCode: "pg",
    flagColors: ["#000000", "#ce1126"],
  },
  {
    name: "Pitcairn",
    altNames: ["Pitcairn", "Pitcairninseln", "Îles Pitcairn", "Islas Pitcairn"],
    countryCode: "pn",
    flagColors: ["#002395", "#fcd116"],
  },
  {
    name: "Samoa",
    altNames: ["Samoa", "Samoa", "Samoa", "Samoa"],
    countryCode: "ws",
    flagColors: ["#ce1126", "#002b7f"],
  },
  {
    name: "Solomon Islands",
    altNames: ["Wyspy Salomona", "Salomonen", "Îles Salomon", "Islas Salomón"],
    countryCode: "sb",
    flagColors: ["#215b33", "#0051ba"],
  },
  {
    name: "Tokelau",
    altNames: ["Tokelau", "Tokelau", "Tokelau", "Tokelau"],
    countryCode: "tk",
    flagColors: ["#002b7f", "#fcd116"],
  },
  {
    name: "Tonga",
    altNames: ["Tonga", "Tonga", "Tonga", "Tonga"],
    countryCode: "to",
    flagColors: ["#c10000", "#ffffff"],
  },
  {
    name: "Tuvalu",
    altNames: ["Tuvalu", "Tuvalu", "Tuvalu", "Tuvalu"],
    countryCode: "tv",
    flagColors: ["#4189dd", "#ffcc00"],
  },
  {
    name: "Vanuatu",
    altNames: ["Vanuatu", "Vanuatu", "Vanuatu", "Vanuatu"],
    countryCode: "vu",
    flagColors: ["#000000", "#ce1126"],
  },
  {
    name: "Wallis and Futuna",
    altNames: ["Wallis i Futuna", "Wallis und Futuna", "Wallis-et-Futuna", "Wallis y Futuna"],
    countryCode: "wf",
    flagColors: ["#002395", "#ed2939"],
  },
  {
    name: "Argentina",
    altNames: ["Argentyna", "Argentinien", "Argentine", "Argentina"],
    countryCode: "ar",
    flagColors: ["#74acdf", "#ffffff"],
  },
  {
    name: "Aruba",
    altNames: ["Aruba", "Aruba", "Aruba", "Aruba"],
    countryCode: "aw",
    flagColors: ["#4189dd", "#f9d616"],
  },
  {
    name: "Bolivia",
    altNames: ["Boliwia", "Bolivien", "Bolivie", "Bolivia"],
    countryCode: "bo",
    flagColors: ["#d52b1e", "#007934"],
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    altNames: ["Bonaire, Sint Eustatius i Saba", "Bonaire, Sint Eustatius und Saba", "Bonaire, Saint-Eustache et Saba", "Bonaire, San Eustaquio y Saba"],
    countryCode: "bq",
    flagColors: ["#21468b", "#ae1c28"],
  },
  {
    name: "Brazil",
    altNames: ["Brazylia", "Brasilien", "Brésil", "Brasil"],
    countryCode: "br",
    flagColors: ["#009739", "#fedd00"],
  },
  {
    name: "Chile",
    altNames: ["Chile", "Chile", "Chili", "Chile"],
    countryCode: "cl",
    flagColors: ["#0039a6", "#d52b1e"],
  },
  {
    name: "Colombia",
    altNames: ["Kolumbia", "Kolumbien", "Colombie", "Colombia"],
    countryCode: "co",
    flagColors: ["#fcd116", "#003893"],
  },
  {
    name: "Curaçao",
    altNames: ["Curaçao", "Curaçao", "Curaçao", "Curazao"],
    countryCode: "cw",
    flagColors: ["#002b7f", "#f9d616"],
  },
  {
    name: "Ecuador",
    altNames: ["Ekwador", "Ecuador", "Équateur", "Ecuador"],
    countryCode: "ec",
    flagColors: ["#ffdd00", "#034694"],
  },
  {
    name: "Falkland Islands",
    altNames: ["Falklandy", "Falklandinseln", "Îles Malouines", "Islas Malvinas"],
    countryCode: "fk",
    flagColors: ["#002395", "#ffffff"],
  },
  {
    name: "French Guiana",
    altNames: ["Gujana Francuska", "Französisch-Guayana", "Guyane française", "Guayana Francesa"],
    countryCode: "gf",
    flagColors: ["#002395", "#ed2939"],
  },
  {
    name: "Guyana",
    altNames: ["Gujana", "Guyana", "Guyana", "Guyana"],
    countryCode: "gy",
    flagColors: ["#009e49", "#ce1126"],
  },
  {
    name: "Paraguay",
    altNames: ["Paragwaj", "Paraguay", "Paraguay", "Paraguay"],
    countryCode: "py",
    flagColors: ["#d52b1e", "#0038a8"],
  },
  {
    name: "Peru",
    altNames: ["Peru", "Peru", "Pérou", "Perú"],
    countryCode: "pe",
    flagColors: ["#d91023", "#ffffff"],
  },
  {
    name: "Suriname",
    altNames: ["Surinam", "Suriname", "Suriname", "Surinam"],
    countryCode: "sr",
    flagColors: ["#b40a2d", "#327832"],
  },
  {
    name: "Trinidad and Tobago",
    altNames: ["Trynidad i Tobago", "Trinidad und Tobago", "Trinité-et-Tobago", "Trinidad y Tobago"],
    countryCode: "tt",
    flagColors: ["#ed1c24", "#000000"],
  },
  {
    name: "Uruguay",
    altNames: ["Urugwaj", "Uruguay", "Uruguay", "Uruguay"],
    countryCode: "uy",
    flagColors: ["#ffffff", "#0038a8"],
  },
  {
    name: "Venezuela",
    altNames: ["Wenezuela", "Venezuela", "Venezuela", "Venezuela"],
    countryCode: "ve",
    flagColors: ["#fce300", "#003da5"],
  }
];

export function getCountryCode(name: string): string {
    return COUNTRIES.find(c => c.name === name)?.countryCode || "xx";
}

export function getFlagColors(name: string): string[] {
    return COUNTRIES.find(c => c.name === name)?.flagColors || ["#eb0273", "#010a40"];
}